name: wheels

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macOS-11]

    steps:
      - uses: actions/checkout@v4

      # Used to host cibuildwheel
      - uses: actions/setup-python@v3

      - name: Build wheels
        run: |
            python -m pip install --upgrade pip
            python -m pip wheel -w wheelhouse .

      - name: Install hungariest_city from wheel
        run: python -m pip install wheelhouse/hungariest_city*.whl

      - name: Test wheel
        run: |
            python -m pip install pytest
            pytest

      # - uses: actions/upload-artifact@v4
      #   with:
      #     name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
      #     path: ./wheelhouse/*.whl
